import React from 'react'
import Head from 'next/head'
import Footer from '../components/Footer'
import hm_l from "/styles/light/Home.module.css";
import TopBar from '../components/TopBar';

let hm = hm_l

function RootLayout({children}) {
  return (
    <>
     <Head>
        <title>Direct Private Offers | Receipts and Analytics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/handshake.png" />
    </Head>
    <TopBar mode={hm} />
    <main>{children}</main>
    <Footer mode={hm} />
    </>
  )
}

export default RootLayout